apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: dapp
  name: dapp
spec:
  serviceAccountName: all-purpose-user
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dapp
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/docker-ethereum-default: "true"
        io.kompose.service: dapp
    spec:
      containers:
        - image: chargaoshou/dockerethbackend:v5.3
          name: dapp
          ports:
            - containerPort: 4000
              hostPort: 4000
              protocol: TCP
          resources:
            limits:
              cpu: "0.3"
              memory: "512Mi"
            requests:
              cpu: "0.15"
              memory: "256Mi"
      restartPolicy: Always
