apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: dockerethganache
  name: dockerethganache
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dockerethganache
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/docker-ethereum-default: "true"
        io.kompose.service: dockerethganache
    spec:
      serviceAccountName: all-purpose-user
      containers:
        - image: chargaoshou/dockerethganache:latest
          name: dockerethganache
          ports:
            - containerPort: 8545
              hostPort: 8545
              protocol: TCP
          resources:
            limits:
              cpu: "0.1"
              memory: "512Mi"
      restartPolicy: Always
